version: '3.5'

services:
  ui:
    image: garr-workshop/ui:1.0
    deploy:
      labels:
      - 'traefik.port=80'
      - 'traefik.frontend.rule=PathPrefix: /'
  thermostat:
    image: garr-workshop/thermostat:1.0
    environment:
    - REDIS_HOST=redis
    #health: curl localhost:8080/actuator/health
    deploy:
      labels:
      - 'traefik.port=8080'
      - 'traefik.frontend.rule=PathPrefix: /api/thermostat'
  humidity:
    image: garr-workshop/humidity:1.0
    deploy:
      labels:
      - 'traefik.port=80'
      - 'traefik.frontend.rule=PathPrefix: /api/humidity/'
    environment:
    - MYSQL_PASSWORD=pww
    - MYSQL_HOST=mysql
  temperature:
      image: garr-workshop/temperature:1.0
      deploy:
        labels:
        - 'traefik.port=5000'
        - 'traefik.frontend.rule=PathPrefix: /api/temperature'
  redis:
    image: redis:alpine
  mysql:
    image: mysql:5.6
    environment:
    - MYSQL_ROOT_PASSWORD=pww
  traefik:
    image: traefik
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - 80:80
    - 8080:8080
    command: '-L debug --docker --docker.swarmMode --docker.domain=traefik --docker.watch --api'


#networks: {}
#volumes: {}

# TODO: user, healthcheck, custom networks, constraints?